### ISSUE TITLE
Animated gif playback is broken

### ISSUE THREAD

**Issue by vitorgalvao** [Nyx0uf/qlImageSize#12]
Had been wondering for a long while why animated gifs no longer played in quicklook. Just confirmed repeatedly it’s qlImageSize that’s doing it.

**Comment by Nyx0uf** [comment]
What OS ? Have you other QL plugins installed ? Because It works well for me.

**Comment by vitorgalvao** [comment]
Apologies for forgetting to post system information; I know it is annoying.

I had no other QL plugins installed (I’ve removed them all to make sure qlImageSize really was the culprit. However, after reinstalling, it seems to be fixed.

Oh, well. Sorry for the noise, and thank you.
