### ISSUE TITLE
Any way to remove extension overly on thumbnails in Finder for common filetypes?

### ISSUE THREAD

**Issue by zikman23** [Nyx0uf/qlImageSize#14]
Is there any way to have it so it doesn't overlay the extension for all the common image filetypes, and just the ones that are not natively supported? I tried poking around in the code but couldn't figure it out.

**Comment by Nyx0uf** [comment]
It's possible, you need to edit the `GenerateThumbnailForURL.m` file and add a condition for the properties dictionary to meet your wish.

Don't submit a PR though because I won't merge it, I like it as it is.

**Comment by dz86** [comment]
Please, explain how to remove all extension on thumbnail in Finder, Thank you
