### ISSUE TITLE
how to remove all extension on thumbnail in Finder?

### ISSUE THREAD

**Issue by dz86** [Nyx0uf/qlImageSize#15]
Please, explain how to remove all extension on thumbnail in Finder, Thank you

**Comment by Nyx0uf** [comment]
in the GenerateThumbnailForURL.m file set the properties dictionary to nil.

**Comment by dz86** [comment]
sorry, but i completely don't understand, can you give the file or say on what string and what needs to change. thank you

**Comment by Nyx0uf** [comment]
I can't be clearer.

If you want this you need to download and build the project yourself and edit the file I mentioned earlier.

**Comment by dz86** [comment]
yes, i did it, but how change properties dictionary to nil, in what string?
