### ISSUE TITLE
Any chance for DPI to be included in the bar?

### ISSUE THREAD

**Issue by brocky27** [Nyx0uf/qlImageSize#22]

**Comment by Nyx0uf** [comment]
If more people are interested, why not.

**Comment by adaringdesign** [comment]
I'd be interested, that would be a useful feature to me!

**Comment by Nyx0uf** [comment]
done in https://github.com/Nyx0uf/qlImageSize/commit/16bf701b09c7c8e7ec059b9197dd380690bb34c9
