### ISSUE TITLE
Installer uses incorrect permissions for QuickLook plugin in ~/Library

### ISSUE THREAD

**Issue by hassankhan** [Nyx0uf/qlImageSize#24]
Hi there,

I installed qlImageSize through Homebrew Cask, the Spotlight plugin worked fine but there was absolutely no change to QuickLook whatsoever.

Upon further inspection, I noticed that in `~/Library/QuickLook/qlImageSize.qlgenerator/` was owned by `root` with permissions `drwx------`/`700`. Upon running `sudo chmod 755 qlImageSize.qlgenerator/ && chown -R $(whoami) qlImageSize.qlgenerator/` it worked perfectly.

**Comment by Nyx0uf** [comment]
Dup of #19
