### ISSUE TITLE
Does not work in Mac OS 10.12.4

### ISSUE THREAD

**Issue by tangxiadi** [Nyx0uf/qlImageSize#26]
![Image of Yaktocat](http://tangxiadi.github.io/images/quick-look-plugins.png)

**Comment by gcm44** [comment]
I have the same issue

**Comment by windyinsc** [comment]
Just wanted to confirm the same issue (not working) in macOS 10.12.5. 
![qllmagesize-qlgenerator-failing](https://user-images.githubusercontent.com/4738933/27261846-4617790a-5419-11e7-878d-f6af5d8e2663.png)

**Comment by joeyhoer** [comment]
I built from source on 10.12.5, and the plugin works. I'm guessing the release is bugged.

**Comment by Nyx0uf** [comment]
Closing, since it is homebrew related.
