### ISSUE TITLE
Support for install via Homebrew cask?

### ISSUE THREAD

**Issue by varunyellina** [Nyx0uf/qlImageSize#28]
As the title says, could you make a homebrew cask installer for this?

It would make it easier to install using an install script when setting up system.

**Comment by varunyellina** [comment]
Sorry for the trouble. There is already a cask for this. `brew cask install qlimagesize`

**Comment by xareelee** [comment]
I can't install `qlImageSize` via homebrew cask:

```
$ brew cask install qlimagesize                         
Error: Cask 'qlimagesize' is unavailable: No Cask with this name exists.
```

Can anyone help?

**Comment by jessemillar** [comment]
@xareelee Looks like the maintainer isn't hosting the installer anymore which breaks `brew cask`. https://github.com/Nyx0uf/qlImageSize/issues/30
