### ISSUE TITLE
no more qlImageSize.pkg?

### ISSUE THREAD

**Issue by atipugin** [Nyx0uf/qlImageSize#30]
Hi!

Looks like http://repo.whine.fr/qlImageSize.pkg doesn't exist anymore. [Homebrew formula](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qlimagesize.rb) relies on it. Any plans to return `pkg` file back?

**Comment by Nyx0uf** [comment]
Hello,

No, I won't re-upload / host any compiled version of this. You'll have to build it yourself or ask someone to do it and host it somewhere.

**Comment by L1cardo** [comment]
you can go to my [repo](https://github.com/L1cardo/qlImageSize)  to install

**Comment by tortoo** [comment]
@L1cardo But still don't know how to install. After unzipping there isn't a file named qlImageSize.qlgenerator.😖
