### ISSUE TITLE
Any installers for this?

### ISSUE THREAD

**Issue by aeon3** [Nyx0uf/qlImageSize#31]
I have no idea how to "compile" qlimagesize myself. I'm completely illiterate when it comes to coding and all.
Where can I find a regular installer or .dmg for this?

**Comment by Nyx0uf** [comment]
Not here, and I won't make one.

**Comment by L1cardo** [comment]
you can go to my [repo](https://github.com/L1cardo/qlImageSize)  to install

**Comment by aeon3** [comment]
> you can go to my [repo](https://github.com/L1cardo/qlImageSize) to install

hey thanks!

I tried using this: brew cask install qlimagesize

But it says: Cask 'qlimagesize' is unavailable: No Cask with this name exists.

Any ideas?

**Comment by joingithubforqlimagesize** [comment]
@L1cardo, I have the same issue as @aeon3:

`Error: Cask 'qlimagesize' is unavailable: No Cask with this name exists.`

Removing the .pkg from the available casks as abruptly by @Nyx0uf has also prevented `brew cask list` from operating correctly, displaying the same error as above, and prevents `brew uninstall` from operating correctly as well.

**Comment by Nyx0uf** [comment]
Can you discuss this somewhere else because homebrew as nothing to do with this. Please use issues for issue with the plugin itself.

Thank you very much.

**Comment by L1cardo** [comment]
@joingithubforqlimagesize  
I am working on it.
I give it to the homebrew , but the has not applied now.
you can discuss this in my repo

**Comment by L1cardo** [comment]
> > you can go to my [repo](https://github.com/L1cardo/qlImageSize) to install
> 
> hey thanks!
> 
> I tried using this: brew cask install qlimagesize
> 
> But it says: Cask 'qlimagesize' is unavailable: No Cask with this name exists.
> 
> Any ideas?

I am working on it.
I give it to the homebrew , but the has not applied now.
you can discuss this in my repo
