### ISSUE TITLE
Installation Guide 

### ISSUE THREAD

**Issue by L1cardo** [Nyx0uf/qlImageSize#33]
For those who want to install this plugin , you can all go to my[ repo ](https://github.com/L1cardo/qlImageSize)
Since the developer will not host and compile the plugin，I will.
If it is not OK for you @Nyx0uf , let me know , and I will delete my repo.

**Comment by L1cardo** [comment]
And if you don't mind , you can transfer the  ownership to me.  hahahahaha
just kidding

**Comment by Nyx0uf** [comment]
ok thanks, I edited the readme.
