### ISSUE TITLE
Install instructions currently broken

### ISSUE THREAD

**Issue by flekschas** [Nyx0uf/qlImageSize#40]
Given the most recent fix in #38 it should be noted in the Readme that

> Using Homebrew Cask : `brew cask install qlimagesize`.

is currently broken. At least for me (on macOS 10.14.3) it didn't work and it also didn't install the spotlight extension.

Since this is advertised as the first option I assume most people choose homebrew over manually installing it. So I think it's worth mentioning that people should rather use your source.

By the way, awesome QL extension 👏👍

**Comment by Nyx0uf** [comment]
Just tried and it works for me.
To be honest I don't care about Homebrew, I'm not the one who made the formula and I don't want to waste my time dealing with thing other than the plugin itself.

Anyway, thanks for the feedback
