### ISSUE TITLE
Does it work on macOS 10.14.5 (18F132)?

### ISSUE THREAD

**Issue by johan456789** [Nyx0uf/qlImageSize#42]
Does it work on macOS 10.14.5 (18F132)? I'm running latest qlImageSize (2.6.1). There's no info shown for any image.

**Comment by Nyx0uf** [comment]
yes it works.

**Comment by philipmarnef** [comment]
It doesn't work for me either. I'm on the same Mojave version. The plugin is listed when I run `qlmanage -m`, but no image dimensions when previewing images in quicklook.
