### ISSUE TITLE
qlImageSize doesn't seem to replace built-in QuickLook image?

### ISSUE THREAD

**Issue by ajeg** [Nyx0uf/qlImageSize#44]
MacOS Mojave 10.14.5.
I downloaded the qlImageSize plugin, moved the '.qlgenerator' file to my ~Library/QuickLook folder, restarted my Mac, but after it came back up again, any image I select and 'spacebar' to get the QuickLook preview just shows the standard/builtin QuickLook preview.

Is there anything that needs to be done to disable the built-in image QuickLook? Does qlImageSize work with Mojave?

Thanks for any help.

**Comment by Nyx0uf** [comment]
Works fine here on 10.14.6. Don't you have another plugin in the way ?

**Comment by Nyx0uf** [comment]
Not reproduced, no more infos -> closing.

**Comment by danielzen** [comment]
The problem for me was Google Drive File Stream, specifically:

`/Applications/Google Drive File Stream.app/Contents/Library/QuickLook/Google Drive File Stream Quick Look.qlgenerator`
