### ISSUE TITLE
DDS files

### ISSUE THREAD

**Issue by Darklocq** [Nyx0uf/qlImageSize#47]
Would be super-awesome if this supported DDS texture files (most common UV texture mapping format used in video games; modders have to work with it ALL the time).  Probably the fastest route to re-usable code for it is the GIMP DDS Plugin: https://code.google.com/archive/p/gimp-dds/

Given that I have to bypass Pixelmator (manually, every time I upgrade it), DDS support is probably the only sufficient draw for me to use qlImageSize.  (I like the size stuff you're doing, but would be actually be happy with any qlgenerator that will view this format without me having to fully open it in GIMP, Photoshop, or GraphicConverter).

**Comment by Nyx0uf** [comment]
Won't do.

Letting the issue open is someone wants to do it.
