### ISSUE TITLE
Definition error

### ISSUE THREAD

**Issue by Evertt** [Nyx0uf/qlImageSize#50]
I get the following error, even when I'm using brew to do things that have nothing to do with this formula.

    Error: Cask 'mdimagesizemdimporter' definition is invalid: invalid 'mdimporter' stanza: key not found: :mdimporterdir

I can't even run `brew cask uninstall mdimagesizemdimporter` anymore, because it exits with the same error.

**Comment by Evertt** [comment]
By the way, here's a temporary terrible fix. Just delete the cask definitions from your computer. Obviously then you can't use the definitions anymore, but the casks themself stay installed (in case you had them installed).  Run the following commands in terminal:

```bash
rm -f /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mdimagesizemdimporter.rb
rm -f /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/mdimagesizemdimporter.rb
```

It only works temporarily though, because as soon as Homebrew updates itself, it stashes the changes you've made, effectively undoing them. It does give you instructions on how to reapply the changes after the update, so that's nice. Maybe you could commit your changes, so that they don't get reset at every update, but I'm hesitant to do that. Because I don't want my local homebrew git repository to start to deviate from the remote one, which may create conflicts with some future update.

**Comment by Nyx0uf** [comment]
Ask the people who maintain brew formulae, because it's not me.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qlimagesize.rb
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mdimagesizemdimporter.rb
