### ISSUE TITLE
Preview not showing image dimensions in Catalina 

### ISSUE THREAD

**Issue by TheModMaster8** [Nyx0uf/qlImageSize#54]
@Nyx0uf After upgrading from Mojave to Catalina, qlImageSize stopped working, after some investigation I discovered that under "System Preferences  -> security & privacy -> General" , it was being block by the OS, as (to my understanding) it sees the plugin as malware due to the lack of a certificate/signing. I tried uninstalling with the command mentioned in the README file, i also tried manually installing it, and i tried compiling it myself through XCode as mention in the README. (with every (un)install i ran `qlmanage -h` and then `qlmanage -h cache` followed by a restart) still nothing was working so I tried the following commands mentioned from here [https://github.com/sindresorhus/quick-look-plugins](url). in terminal with and without sudo permissions...`xattr -r ~/Library/QuickLook`  followed by `xattr -d -r com.apple.quarantine ~/Library/QuickLook`. still nothing, so i finally tried `sudo spctl --master-disable` (NOT recommended) and still nothing. so I'm at a lose now and i can't figure out if it is due to the Catalina update or if it is something I am messing up, if you could advise me or look into this, It would be very much appreciated.

**Comment by TheModMaster8** [comment]
after doing some more digging i found [this](https://github.com/srirangav/qlImagePreviewWithSize) post that stated "
 4. This quicklook generator will not work on Catalina (10.15.4) or 
       later because Apple no longer allows third party quicklook 
       generators to override the default quicklook generator for 
       public.image.
this may be what is wrong. but im guessing at this point

**Comment by Nyx0uf** [comment]
see https://github.com/Nyx0uf/qlImageSize/issues/45
