### ISSUE TITLE
Homebrew install doesn't work

### ISSUE THREAD

**Issue by sindresorhus** [Nyx0uf/qlImageSize#9]
```
❯ brew cask install qlimagesize
==> Downloading http://repo.whine.fr/qlImageSize.qlgenerator-10.8.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'qlimagesize' with message: Download failed: http://repo.whine.fr/qlImageSize.qlgenerator-10.8.zip
```

You should update the cask to this GitHub repo instead.

**Comment by macx** [comment]
@sindresorhus It's still an issue: `Download failed on Cask 'qlimagesize' with message: Download failed: https://repo.whine.fr/qlImageSize.pkg`.

**Comment by Nyx0uf** [comment]
Should be fixed

**Comment by jjeejj** [comment]
@Nyx0uf  I also have this problem now.  my system is MacOS Mojave

curl: (56) Unexpected EOF
Error: Download failed on Cask 'qlimagesize' with message: Download failed: https://repo.whine.fr/qlImageSize.pkg

**Comment by whalesingswee** [comment]
> @Nyx0uf I also have this problem now. my system is MacOS Mojave
> 
> curl: (56) Unexpected EOF
> Error: Download failed on Cask 'qlimagesize' with message: Download failed: https://repo.whine.fr/qlImageSize.pkg

I am having the same problem on newly installed Mojave as well.

**Comment by lonelygo** [comment]
> > @Nyx0uf I also have this problem now. my system is MacOS Mojave
> > curl: (56) Unexpected EOF
> > Error: Download failed on Cask 'qlimagesize' with message: Download failed: https://repo.whine.fr/qlImageSize.pkg
> 
> I am having the same problem on newly installed Mojave as well.

+1
